/** @type {import('tailwindcss').Config} */
export default {
        darkMode: "class",
        content: [
                "./index.html",
                "./src/**/*.{js,ts,jsx,tsx}",
        ],
        theme: {
                extend: {
                        "colors": {
                                "secondary-container": "#00bd85",
                                "surface-bright": "#343b36",
                                "on-tertiary-fixed": "#410005",
                                "on-error-container": "#ffdad6",
                                "inverse-on-surface": "#2b322d",
                                "on-secondary": "#003825",
                                "tertiary-fixed-dim": "#ffb3af",
                                "surface-variant": "var(--gray-light)",
                                "surface-container": "var(--white)",
                                "on-secondary-container": "#00452e",
                                "secondary-fixed-dim": "#45dfa4",
                                "on-tertiary": "#650911",
                                "outline": "var(--gray-border)",
                                "tertiary-fixed": "#ffdad7",
                                "surface-dim": "#0e1511",
                                "on-tertiary-fixed-variant": "#842225",
                                "tertiary": "#ffb3af",
                                "surface": "var(--light)",
                                "surface-container-highest": "var(--gray-light)",
                                "tertiary-container": "#fc7c78",
                                "surface-container-lowest": "#09100c",
                                "primary": "#4edea3",
                                "primary-container": "#10b981",
                                "surface-container-low": "var(--white)",
                                "on-tertiary-container": "#711419",
                                "on-error": "#690005",
                                "on-background": "#dde4dd",
                                "surface-tint": "#4edea3",
                                "error-container": "#93000a",
                                "on-primary-fixed": "#002113",
                                "secondary": "#45dfa4",
                                "background": "var(--light)",
                                "on-primary": "#003824",
                                "on-surface": "var(--dark)",
                                "on-secondary-fixed": "#002114",
                                "outline-variant": "var(--gray-border)",
                                "on-surface-variant": "var(--gray)",
                                "on-secondary-fixed-variant": "#005137",
                                "primary-fixed-dim": "#4edea3",
                                "surface-container-high": "#242c27",
                                "primary-fixed": "#6ffbbe",
                                "inverse-primary": "#006c49",
                                "on-primary-fixed-variant": "#005236",
                                "inverse-surface": "#dde4dd",
                                "on-primary-container": "#00422b",
                                "error": "#ffb4ab",
                                "secondary-fixed": "#68fcbf"
                        },
                        "borderRadius": {
                                "DEFAULT": "0.25rem",
                                "lg": "0.5rem",
                                "xl": "0.75rem",
                                "full": "9999px"
                        },
                        "spacing": {
                                "stack-lg": "32px",
                                "stack-xl": "64px",
                                "container-max": "1440px",
                                "edge-margin-mobile": "24px",
                                "gutter": "24px",
                                "stack-md": "16px",
                                "edge-margin-desktop": "80px"
                        },
                        "fontFamily": {
                                "headline-md": ["Inter"],
                                "label-caps": ["Inter"],
                                "headline-lg": ["Inter"],
                                "headline-lg-mobile": ["Inter"],
                                "display-hero": ["Inter"],
                                "body-md": ["Inter"],
                                "body-lg": ["Inter"]
                        },
                        "fontSize": {
                                "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                                "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
                                "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
                                "headline-lg-mobile": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                                "display-hero": ["84px", { "lineHeight": "90px", "letterSpacing": "-0.04em", "fontWeight": "800" }],
                                "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0", "fontWeight": "400" }],
                                "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0", "fontWeight": "400" }]
                        }
                }
        },
        plugins: [],
}
